name: Update Version on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'  # Triggers on semantic version tags with 'v' prefix (e.g., v1.0.0, v2.1.3-alpha, v0.9.1-beta.1)
      - '[0-9]+.[0-9]+.[0-9]+**'   # Triggers on semantic version tags without 'v' prefix (e.g., 1.0.0, 2.1.3-alpha)

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      id: extract_version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        # Remove 'v' prefix if it exists
        VERSION=${TAG_NAME#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"

    - name: Update version in __init__.py
      run: |
        VERSION="${{ steps.extract_version.outputs.version }}"
        INIT_FILE="medis/__init__.py"

        if [ -f "$INIT_FILE" ]; then
          # Update the __version__ line
          sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" "$INIT_FILE"
          echo "Updated $INIT_FILE with version $VERSION"

          # Show the change
          echo "New content:"
          cat "$INIT_FILE"
        else
          echo "Error: $INIT_FILE not found"
          exit 1
        fi

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git diff
        fi

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add medis/__init__.py
        git commit -m "chore: update version to ${{ steps.extract_version.outputs.version }} for tag ${{ steps.extract_version.outputs.tag_name }}"

        # Push to the default branch (usually main or master)
        git push origin HEAD:main

        echo "Version updated and committed successfully"

    - name: Create summary
      run: |
        echo "## Version Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag:** ${{ steps.extract_version.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** ${{ steps.extract_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **File Updated:** medis/__init__.py" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
          echo "- **Status:** ✅ Version updated and committed" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status:** ℹ️ No changes needed (version already matches)" >> $GITHUB_STEP_SUMMARY
        fi
